export const ADD_ALARM = "ADD_ALARM";
export const SET_PLACEHOLDER = "SET_ALARM_PLACEHOLDER";
export const ADD_ALARMS = "ADD_ALARMS";
export const SET_TOGGLER = "SET_TOGGLER";
export const TOGGLE_DELETE_LIST = "TOGGLE_DELETE_LIST";
export const TOGGLE_ALARM_CHECK = "TOGGLE_ALARM_CHECK";
export const DELETE_SELECTED_ALARMS = "DELETE_SELECTED_ALARMS";