export const INCREMENT_HOUR = "INCREMENT_HOUR";
export const INCREMENT_MINUTE = "INCREMENT_MINUTE";
export const INCREMENT_SECOND = "INCREMENT_SECOND";
export const INCREMENT_MILLISECONDBYTEN = "INCREMENT_MILLISECONDBYTEN";
export const RESET_STOPWATCH = "RESET_STOPWATCH";
export const ADD_MARK = "ADD_MARK";
export const ACTIVATE = "ACTIVATE";
export const DEACTIVATE = "DEACTIVATE";
